name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to remote server
      env:
        SSH_PRIVATE_KEY: jroAiU0CqqonD0yLcBjJSa6e7R8zzMzMKbgRPwhXUQI
        REMOTE_HOST: 172.23.52.254
        REMOTE_USER: arsalane
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan $REMOTE_HOST >> ~/.ssh/known_hosts

        scp -r . $REMOTE_USER@$REMOTE_HOST:/path/to/your/project

        ssh $REMOTE_USER@$REMOTE_HOST << 'EOF'
          cd /path/to/your/project
          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          # Run any other deployment steps, e.g., restarting services
          # Example: sudo systemctl restart your_service
        EOF
